# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170825_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklogdetail',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklogdetail',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
